language: node_js

node_js:
  - "6"

before_install:
   - gem install sass

script:
   - ./build.sh
   
deploy:
  provider: s3
  access_key_id: $S3_KEY
  secret_access_key: $S3_SECRET
  bucket: tilosdeploy
  acl: public_read
  local_dir: build
  skip_cleanup: true
